version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: careerhub-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: careerhub
      POSTGRES_USER: careerhub
      POSTGRES_PASSWORD: careerhub123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/api/prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - careerhub-network

  redis:
    image: redis:7-alpine
    container_name: careerhub-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - careerhub-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: careerhub-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - '9200:9200'
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - careerhub-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: careerhub-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - careerhub-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  careerhub-network:
    driver: bridge
