services:
  - type: web
    name: deve-way
    runtime: node
    rootDir: apps/api
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  - type: web
    name: deveWay-learn
    runtime: node
    rootDir: apps/learn
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002