-- Add keywords column to career_paths table
ALTER TABLE career_paths ADD COLUMN IF NOT EXISTS keywords text[] DEFAULT '{}';

-- Seed career paths with keywords (run this after the column is added)
INSERT INTO career_paths (id, slug, title_en, title_ar, description_en, description_ar, salary_range_en, salary_range_ar, job_titles_en, job_titles_ar, demand_level, keywords, is_active, sort_order)
VALUES
  (gen_random_uuid(), 'backend', 'Backend Development', 'تطوير الواجهة الخلفية', 'Backend development career path', 'مسار تطوير الواجهة الخلفية', '{"min":15000,"max":45000,"currency":"EGP"}', '{"min":15000,"max":45000,"currency":"EGP"}', '{"Backend Developer","API Developer"}', '{"مطور الواجهة الخلفية","مطور واجهات برمجية"}', 'HIGH', '{"backend","node","api","server","database","python","django"}', true, 1),
  (gen_random_uuid(), 'frontend', 'Frontend Development', 'تطوير الواجهة الأمامية', 'Frontend development career path', 'مسار تطوير الواجهة الأمامية', '{"min":12000,"max":40000,"currency":"EGP"}', '{"min":12000,"max":40000,"currency":"EGP"}', '{"Frontend Developer","UI Developer"}', '{"مطور الواجهة الأمامية","مطور واجهة المستخدم"}', 'HIGH', '{"frontend","react","vue","css","html","javascript","ui"}', true, 2),
  (gen_random_uuid(), 'fullstack', 'Full Stack Development', 'تطوير الويب الشامل', 'Full stack development career path', 'مسار تطوير الويب الشامل', '{"min":18000,"max":55000,"currency":"EGP"}', '{"min":18000,"max":55000,"currency":"EGP"}', '{"Full Stack Developer","MERN Developer"}', '{"مطور الويب الشامل","مطور MERN"}', 'HIGH', '{"fullstack","mern","web","javascript","react","node"}', true, 3),
  (gen_random_uuid(), 'cybersecurity', 'Cybersecurity', 'الأمن السيبراني', 'Cybersecurity career path', 'مسار الأمن السيبراني', '{"min":20000,"max":60000,"currency":"EGP"}', '{"min":20000,"max":60000,"currency":"EGP"}', '{"Security Engineer","Penetration Tester"}', '{"مهندس أمن","مخترق قبعات بيضاء"}', 'HIGH', '{"security","hacking","kali","linux","network","ethical","cyber"}', true, 4),
  (gen_random_uuid(), 'devops', 'DevOps & Cloud', 'ديف أوبس والسحابة', 'DevOps and cloud career path', 'مسار ديف أوبس والسحابة', '{"min":18000,"max":50000,"currency":"EGP"}', '{"min":18000,"max":50000,"currency":"EGP"}', '{"DevOps Engineer","Cloud Architect"}', '{"مهندس ديف أوبس","معماري السحابة"}', 'HIGH', '{"devops","docker","linux","aws","cloud","kubernetes","cicd"}', true, 5),
  (gen_random_uuid(), 'data-science', 'Data Science & AI', 'علم البيانات والذكاء الاصطناعي', 'Data science and AI career path', 'مسار علم البيانات والذكاء الاصطناعي', '{"min":20000,"max":60000,"currency":"EGP"}', '{"min":20000,"max":60000,"currency":"EGP"}', '{"Data Scientist","ML Engineer"}', '{"عالم بيانات","مهندس تعلم آلي"}', 'HIGH', '{"data","python","machine learning","ai","analytics","pandas"}', true, 6),
  (gen_random_uuid(), 'mobile', 'Mobile Development', 'تطوير التطبيقات', 'Mobile development career path', 'مسار تطوير التطبيقات', '{"min":15000,"max":45000,"currency":"EGP"}', '{"min":15000,"max":45000,"currency":"EGP"}', '{"Mobile Developer","React Native Developer"}', '{"مطور تطبيقات","مطور React Native"}', 'MEDIUM', '{"mobile","react native","flutter","android","ios"}', true, 7),
  (gen_random_uuid(), 'ui-ux', 'UI/UX Design', 'تصميم تجربة المستخدم', 'UI/UX design career path', 'مسار تصميم تجربة المستخدم', '{"min":12000,"max":40000,"currency":"EGP"}', '{"min":12000,"max":40000,"currency":"EGP"}', '{"UI Designer","UX Researcher"}', '{"مصمم واجهة","باحث تجربة مستخدم"}', 'MEDIUM', '{"design","figma","ux","ui","user experience","prototype"}', true, 8),
  (gen_random_uuid(), 'database', 'Database Engineering', 'هندسة قواعد البيانات', 'Database engineering career path', 'مسار هندسة قواعد البيانات', '{"min":15000,"max":45000,"currency":"EGP"}', '{"min":15000,"max":45000,"currency":"EGP"}', '{"Database Administrator","Data Engineer"}', '{"مدير قواعد بيانات","مهندس بيانات"}', 'MEDIUM', '{"database","sql","postgresql","mysql","mongodb","data"}', true, 9),
  (gen_random_uuid(), 'game-dev', 'Game Development', 'تطوير الألعاب', 'Game development career path', 'مسار تطوير الألعاب', '{"min":18000,"max":50000,"currency":"EGP"}', '{"min":18000,"max":50000,"currency":"EGP"}', '{"Game Developer","Unity Developer"}', '{"مطور ألعاب","مطور Unity"}', 'MEDIUM', '{"game","unity","unreal","csharp","gamedev","3d"}', true, 10)
ON CONFLICT (slug) DO UPDATE SET
  keywords = EXCLUDED.keywords,
  title_en = EXCLUDED.title_en,
  title_ar = EXCLUDED.title_ar,
  description_en = EXCLUDED.description_en,
  description_ar = EXCLUDED.description_ar;
